### ISSUE TITLE
Góp ý cho đồ án của nhóm: 

### ISSUE THREAD

**Issue by NguyenNamAnh-201** [NguyenNamAnh-201/P4DS_FinalProject#1]
Bài của chúng tớ gần hoàn thành, cần bổ sung thêm cho phần trực quan hóa dữ liệu. 
Cảm ơn bạn đã đọc.
Mời bạn góp ý !

**Comment by vietsimon** [comment]
![image](https://user-images.githubusercontent.com/56797865/149453626-2d60a6f4-586a-49f4-9f7c-1e6b8e4a5800.png)
Nhóm bạn thử dùng câu lệnh plt.show() có ẩn đi mấy đoạn như trên hình.

**Comment by vietsimon** [comment]
![image](https://user-images.githubusercontent.com/56797865/149453990-c10fc0b9-7c72-487b-85f1-1bd5492ff107.png)
Chưa xử lí giá trị thiếu

**Comment by vietsimon** [comment]
![image](https://user-images.githubusercontent.com/56797865/149454282-006ded73-c2ff-4d67-86b3-c6d8388716c3.png)
Chưa nêu được ý của câu hỏi, nghĩa là tìm câu trả lời cho câu hỏi đó để làm gì ?

**Comment by vietsimon** [comment]
![image](https://user-images.githubusercontent.com/56797865/149454725-8e4ed5df-1c1b-4d2d-a77f-6568509219d0.png)
Câu này chưa thấy biểu đồ và nhận xét biểu đồ và đưa ra câu trả lời cho câu hỏi ?

**Comment by chopcolate** [comment]
Chào mn, mình là Trung từ nhóm 19, mình xin góp ý về nhóm bạn như sau:
- Bài làm đầy đủ, có thêm mô hình học máy, số lượng câu hỏi ở mức trung bình(không quá khó cũng không quá dễ).
- Quá trình tiền xử lí giá trị thiếu vẫn chưa có, biểu đồ trực quan ở câu hỏi 4.2.1 chưa có(có thể do chưa chạy cell code),  những điều rút ra được sau mỗi quá trình mình nghĩ cần chi tiết hơn
![image](https://user-images.githubusercontent.com/64058709/149464638-0a87918a-8ead-4eb5-a072-a4fdb2a4f529.png)
Không nên viết tắt nữa nhé

**Comment by vietsimon** [comment]
Chào nhóm 20.Mình là Trần Quốc Việt đến từ  nhóm 19 xin nhân xét bài làm của nhóm bạn
1. Nhóm bạn thử dùng câu lệnh plt.show() có ẩn đi mấy đoạn như trên hình, mấy chỗ khác cũng tương tự
![image](https://user-images.githubusercontent.com/56797865/149453626-2d60a6f4-586a-49f4-9f7c-1e6b8e4a5800.png)
2. Các câu hỏi cần nêu thêm ý nghĩa , tức là tìm câu trả lời cho câu hỏi đó để làm gì, nhằm mục đích gì ?

**Comment by NguyenNamAnh-201** [comment]
> Chào mn, mình là Trung từ nhóm 19, mình xin góp ý về nhóm bạn như sau:
> 
> * Bài làm đầy đủ, có thêm mô hình học máy, số lượng câu hỏi ở mức trung bình(không quá khó cũng không quá dễ).
> * Quá trình tiền xử lí giá trị thiếu vẫn chưa có, biểu đồ trực quan ở câu hỏi 4.2.1 chưa có(có thể do chưa chạy cell code),  những điều rút ra được sau mỗi quá trình mình nghĩ cần chi tiết hơn
>   ![image](https://user-images.githubusercontent.com/64058709/149464638-0a87918a-8ead-4eb5-a072-a4fdb2a4f529.png)
>   Không nên viết tắt nữa nhé
